### ISSUE TITLE
Feature request: Add flags to clear the console and align it vertically in the middle

### ISSUE THREAD

**Issue by felixjulianheitmann** [mordv/mnswpr#3]
Hi,

I would like to be able to clear my console before start, so I don't have the game at the very bottom of my screen. Also I would like the game to be vertically centered, when using the "fullscreen" option.

I tried implementing that myself, but as far as I could see, the Ink framework does not know about the terminal size. One could set the outermost `Box` size to the terminal height, but that would need to be updated dynamically when changing the terminal size.

Thank you for the gift to a slightly obsessed Minesweeper enthusiast.

Cheers

**Comment by mordv** [comment]
@felixjulianheitmann 
At first, I didn't think it would be possible, but I've found [this](https://github.com/vadimdemedes/ink/issues/263#issuecomment-600927688) comment. Turned out you can write commands to stdout to enter and exit fullscreen. I suppose tools like `htop` or `nano` use exactly this. Also turned out you can subscribe to stdout resize, so everything works like a charm, really like how it turned out.

Again, thanks for the ideas, for some reason I didn't think about clearing output at all. 

I have also found [persistant library](https://github.com/sindresorhus/conf) for npm packages, so we might try to track records, PR's are welcome :)
